# Generated by Django 4.0.4 on 2022-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
    ]
