# Generated by Django 4.0.4 on 2022-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.BooleanField(default=False),
        ),
    ]
