# Generated by Django 4.0.4 on 2022-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_user'),
        ('booking', '0002_alter_booking_customer_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=models.SET('account deleted'), to='accounts.customer'),
        ),
    ]
